const colors = {
  light: {
    text: "#1D2D50",
    tint: "#E63946",
    background: "#F8F9FC",
    foreground: "#1D2D50",
    card: "#FFFFFF",
    cardForeground: "#1D2D50",
    primary: "#E63946",
    primaryForeground: "#FFFFFF",
    primaryLight: "#FFF0F1",
    secondary: "#F1F4FB",
    secondaryForeground: "#1D2D50",
    muted: "#F1F4FB",
    mutedForeground: "#7B8CA6",
    accent: "#F5A623",
    accentForeground: "#1D2D50",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E8EDF4",
    input: "#E8EDF4",
    success: "#2DC653",
    successLight: "#EDFAF2",
    gold: "#F5A623",
    goldLight: "#FFF8EC",
    navy: "#1D2D50",
    navyLight: "#EEF1F8",
    purple: "#7C3AED",
    purpleLight: "#F5F0FF",
    pink: "#EC4899",
    pinkLight: "#FDF2F8",
    teal: "#0D9488",
    tealLight: "#F0FDFA",
  },
  radius: 14,
};

export default colors;
